language: objective-c
osx_image: xcode8.1

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace PGDebugView.xcworkspace -scheme PGDebugView -destination 'platform=iOS Simulator,name=iPhone 6s' clean build | xcpretty;
